"""
Data models for compliance reports and findings.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from datetime import datetime
from enum import Enum


class ComplianceStatus(Enum):
    """Enumeration for compliance status."""
    COMPLIANT = "compliant"
    NON_COMPLIANT = "non_compliant"
    PARTIALLY_COMPLIANT = "partially_compliant"
    UNCLEAR = "unclear"


class SeverityLevel(Enum):
    """Enumeration for severity levels."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class ComplianceFinding:
    """Represents a single compliance finding."""
    requirement_id: str
    requirement_text: str
    compliance_status: ComplianceStatus
    gdpr_articles: List[str]
    reasoning: str
    severity: SeverityLevel
    recommendations: List[str] = field(default_factory=list)
    
    # Additional metadata
    confidence_score: Optional[float] = None
    processing_time: Optional[float] = None
    model_used: Optional[str] = None


@dataclass
class ComplianceReport:
    """Represents a compliance report generated by a CC_Agent."""
    agent_id: str
    model_used: str
    findings: List[ComplianceFinding]
    overall_assessment: str
    confidence_score: float
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Document metadata
    document_id: Optional[str] = None
    document_filename: Optional[str] = None
    
    # Processing metadata
    processing_time: Optional[float] = None
    total_requirements_analyzed: Optional[int] = None
    iteration_number: int = 1
    
    def get_findings_by_severity(self, severity: SeverityLevel) -> List[ComplianceFinding]:
        """Get findings filtered by severity level."""
        return [f for f in self.findings if f.severity == severity]
    
    def get_non_compliant_findings(self) -> List[ComplianceFinding]:
        """Get all non-compliant findings."""
        return [f for f in self.findings if f.compliance_status == ComplianceStatus.NON_COMPLIANT]
    
    def get_summary_stats(self) -> Dict[str, int]:
        """Get summary statistics for the report."""
        stats = {
            "total_findings": len(self.findings),
            "compliant": 0,
            "non_compliant": 0,
            "partially_compliant": 0,
            "unclear": 0
        }
        
        for finding in self.findings:
            if finding.compliance_status == ComplianceStatus.COMPLIANT:
                stats["compliant"] += 1
            elif finding.compliance_status == ComplianceStatus.NON_COMPLIANT:
                stats["non_compliant"] += 1
            elif finding.compliance_status == ComplianceStatus.PARTIALLY_COMPLIANT:
                stats["partially_compliant"] += 1
            else:
                stats["unclear"] += 1
        
        return stats


@dataclass
class FinalComplianceReport:
    """Represents the final consolidated compliance report from RA_Agent."""
    consolidated_findings: List[ComplianceFinding]
    overall_compliance_status: str
    confidence_score: float
    timestamp: datetime = field(default_factory=datetime.now)
    
    # Source reports metadata
    source_reports: List[str] = field(default_factory=list)  # Agent IDs
    consolidation_notes: str = ""
    
    # Document metadata
    document_id: Optional[str] = None
    document_filename: Optional[str] = None
    
    # Processing metadata
    total_processing_time: Optional[float] = None
    feedback_iterations: int = 0
    
    def get_critical_findings(self) -> List[ComplianceFinding]:
        """Get all critical severity findings."""
        return [f for f in self.consolidated_findings if f.severity == SeverityLevel.CRITICAL]
    
    def get_compliance_summary(self) -> Dict[str, Any]:
        """Get a comprehensive compliance summary."""
        total_findings = len(self.consolidated_findings)
        non_compliant = len([f for f in self.consolidated_findings 
                           if f.compliance_status == ComplianceStatus.NON_COMPLIANT])
        
        return {
            "total_findings": total_findings,
            "non_compliant_count": non_compliant,
            "compliance_percentage": ((total_findings - non_compliant) / total_findings * 100) if total_findings > 0 else 100,
            "overall_status": self.overall_compliance_status,
            "confidence_score": self.confidence_score,
            "critical_issues": len(self.get_critical_findings())
        }